apiVersion: v1
kind: Service
metadata:
  name: echoserver-direct-service
  labels:
    app: echoserver
spec:
  type: LoadBalancer
  selector:
    app: echoserver
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: http-web-svc